# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
