# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20170824_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('language', models.CharField(default='none', max_length=100)),
                ('snippet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='snippets.Snippet')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.RemoveField(
            model_name='content',
            name='snippet_id',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
