# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20170824_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
