# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0010_auto_20170826_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snippets', to='snippets.Group'),
        ),
    ]
